apiVersion: apps/v1
kind: Deployment

metadata:
  name: event-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: event-service

  template:
    metadata:
      labels:
        app: event-service

    spec:
      containers:
        - name: event-service
          image: ghcr.io/soufiane2204/seatnow-event-service:latest

          ports:
            - containerPort: 8082

          envFrom:
            - configMapRef:
                name: event-config

            - secretRef:
                name: event-secret

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3