apiVersion: apps/v1
kind: Deployment

metadata:
  name: event-db

spec:
  replicas: 1

  selector:
    matchLabels:
      app: event-db

  template:
    metadata:
      labels:
        app: event-db

    spec:
      containers:
        - name: postgres
          image: postgres:17

          env:
            - name: POSTGRES_DB
              value: seatnow_events

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

          ports:
            - containerPort: 5432

          volumeMounts:
            - name: event-db-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: event-db-storage
          persistentVolumeClaim:
            claimName: event-db-data