apiVersion: v1
kind: ConfigMap

metadata:
  name: booking-config

data:
  DB_URL: "jdbc:postgresql://booking-db:5432/seatnow_bookings"
  DB_USERNAME: "postgres"
  EVENT_SERVICE_URL: "http://event-service:8082"